#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.
#
# Copyright 2019, 2022 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: MIT

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

shopt \
    -s nullglob

PATH="${SNAP}/usr/local/bin:${SNAP}/usr/local/sbin:${PATH}"
export ISCAN_FIRMWARE_DIR="${SNAP_USER_COMMON}/firmware"

# Plugin support
mkdir \
    --verbose \
    --parents \
    "${SNAP_USER_COMMON}/state" \
    "${SNAP_USER_COMMON}/firmware" \
    "${SNAP_USER_COMMON}/plugins" \
    "${SNAP_USER_COMMON}/device"

maintainer_notice_read_marker_file="${SNAP_USER_COMMON}/skip-maintainer-notice.marker"
if ! test -e "${maintainer_notice_read_marker_file}"; then
    zenity \
        --title 'Notice from the snap maintainer' \
        --width=640 \
        --info \
        --ok-label='Continue' \
        --text "Hello, this is 林博仁(Buo-ren, Lin), the maintainer of this application snap.\\n\\nI would like to inform you that this is NOT an official distribution of Image Scan! for Linux (V2), please report all issue regarding the use of this snap to the snap's own issue tracker:\\n\\n    Issues · brlin-tw/iscan-snap\\n    https://github.com/brlin-tw/iscan-snap/issues\\n\\nThank you.\\n\\nThis snap includes an EPSON's esmod API wrapper library that is licensed under the EPSON END USER SOFTWARE LICENSE which will be displayed in the next dialog, you will be required to accept the license to continue the usage of this application.\\n\\nThis dialog will only display once, to see it again remove the ${maintainer_notice_read_marker_file} marker file and relaunch the application."
    touch "${maintainer_notice_read_marker_file}"
fi

epson_end_user_software_license_read_marker_file="${SNAP_USER_COMMON}/user-agreed-epson-proprietary-license.marker"
if ! test -e "${epson_end_user_software_license_read_marker_file}"; then
    if ! zenity \
            --title 'EPSON END USER SOFTWARE LICENSE' \
            --width=640 \
            --text-info \
            --checkbox='/usr/local/share/doc/iscan/COPYING.EPSON.en.txt' \
            --ok-label='Continue'; then
        exit 1
    else
        touch "${epson_end_user_software_license_read_marker_file}"
    fi
fi

udev_notice_read_marker_file="${SNAP_USER_COMMON}/skip-udev-notice.marker"
if ! test -e "${udev_notice_read_marker_file}"; then
    zenity \
        --title 'Manual operation required: Udev rules' \
        --width=640 \
        --info \
        --ok-label='Continue' \
        --text "Due to snapd's limitations the snap is unable to install the required udev rules to enable the snap to access the scanners.\\n\\nPlease run the following commands in the terminal to fix it manually:\\n\\n<tt>    iscan.make-policy-file --mode udev --desc-file /snap/iscan/current/usr/local/share/iscan-data/epkowa.desc --force -o 60-iscan.rules\\n    sudo install --owner=root --group=root --mode 0644 60-iscan.rules /etc/udev/rules.d/\\n    sudo udevadm control --reload</tt>\\n\\nThis dialog will only display once, to see it again remove the ${udev_notice_read_marker_file} marker file and relaunch the application."
fi

# Finally run the next part of the command chain
exec "${@}"
