#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.
#
# Copyright 2019, 2022 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: MIT

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

shopt \
    -s nullglob

PATH="${SNAP}/usr/local/bin:${PATH}"
export ISCAN_FIRMWARE_DIR="${SNAP_USER_COMMON}/firmware"

# Plugin support
mkdir \
    --verbose \
    --parents \
    "${SNAP_USER_COMMON}/state" \
    "${SNAP_USER_COMMON}/firmware" \
    "${SNAP_USER_COMMON}/plugins" \
    "${SNAP_USER_COMMON}/device"

# Finally run the next part of the command chain
exec "${@}"
