#!/usr/bin/env bash
# Extract and set the snap's version from the main part
# 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com> © 2019
#
# Copyright 2019, 2022 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: MIT

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

init(){
    local \
        flag_dry_run=false \
        upstream_version \
        packaging_revision \
        some_place_under_the_project_repo \
        snap_version_string

    for commandline_argument in "${@}"; do
        case "${commandline_argument}" in
            # Enable execution tracing
            --debug)
                set -o xtrace
            ;;
            # Don't run snapcraftctl for testing purpose
            --dry-run)
                flag_dry_run=true
            ;;
            --usage)
                print_usage
                exit 0
            ;;
            *)
                printf -- \
                    'main-adopt-info: Error: Invalid command-line argument.\n' \
                    >&2
                print_usage
                exit 1
            ;;
        esac
    done

    iscan_version="$(
        grep \
            --only-matching \
            --perl-regexp \
            '(?<=iscan_)\d+\.\d+\.\d+' \
            "${SNAPCRAFT_PROJECT_DIR}/snap/snapcraft.yaml"
    )"
    iscan_data_version="$(
        grep \
            --only-matching \
            --perl-regexp \
            '(?<=iscan-data_)\d+\.\d+\.\d+' \
            "${SNAPCRAFT_PROJECT_DIR}/snap/snapcraft.yaml"
    )"
    upstream_version="${iscan_version}+data${iscan_data_version}"

    packaging_revision="$(
        git \
            -C "${SNAPCRAFT_PROJECT_DIR}" \
            describe \
            --abbrev=4 \
            --always \
            --match nothing \
            --dirty=-d
    )"

    snap_version_string="${upstream_version}+s${packaging_revision}"

    printf -- \
        'main-adopt-info: Setting snap version to "%s".\n' \
        "${snap_version_string}"
    if [ "${flag_dry_run}" = false ]; then
        snapcraftctl set-version \
            "${snap_version_string}"
    fi

    exit 0
}

print_usage(){
    printf -- 'Usage: main-adopt-info [options] iscan\n'
    printf -- 'options: [--debug|--dry-run|--help]\n'
}

init "${@}"
